### ISSUE TITLE
Payload to large 

### ISSUE THREAD

**Issue by SnaBe** [msd-d/PetHub#70]
```bash
PayloadTooLargeError: request entity too large
    at readStream (/usr/lib/node_modules/expo-cli/node_modules/@expo/dev-server/node_modules/raw-body/index.js:155:17)
    at getRawBody (/usr/lib/node_modules/expo-cli/node_modules/@expo/dev-server/node_modules/raw-body/index.js:108:12)
    at read (/usr/lib/node_modules/expo-cli/node_modules/@expo/dev-server/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/usr/lib/node_modules/expo-cli/node_modules/@expo/dev-server/node_modules/body-parser/lib/types/json.js:135:5)
    at call (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at remoteDevtoolsCorsMiddleware (/usr/lib/node_modules/expo-cli/node_modules/@expo/dev-server/src/middleware/remoteDevtoolsCorsMiddleware.ts:31:3)
    at call (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:239:7)
    at next (/usr/lib/node_modules/expo-cli/node_modules/connect/index.js:183:5)
    at serveStatic (/usr/lib/node_modules/expo-cli/node_modules/serve-static/index.js:75:16)

```
This error seems to originate from some method loading a large amount of data and seems to be troubled by its size. 

I have already verified that this is not caused by console.log, might just be my phone or computer who's slow.

**Comment by Joergenson** [comment]
:yikes:

**Comment by Joergenson** [comment]
det sker kun for mig en gang imellem under et reload

**Comment by SnaBe** [comment]
> det sker kun for mig en gang imellem under et reload

Tænker at min mobile ikke er i stand til håndtere dummy-data og så loade flere billedere i højere kvalitet på samme tid.

**Comment by Joergenson** [comment]
Jaaa men det crasher den ikke vel?

**Comment by SnaBe** [comment]
> Jaaa men det crasher den ikke vel?

Nej, bare rolig :wink:
